apiVersion: agentfile.build/v1
kind: Agent
metadata:
  name: hello-world
spec:
  harness:
    claudecode: {}
    image: myimage:latest
  llm:
    anthropic:
      model: haiku-4.5
  prompt: |
    say hi using the cowsay command!