apiVersion: agentfile.build/v1
kind: Agent
metadata:
  name: hello-world
spec:
  harness:
    claudecode: {}
  llm:
    anthropic:
      model: claude-haiku-4-5
  prompt:
    text: |
      say hi to the user $LOGNAME
  envs:
    - name: CLAUDE_CODE_OAUTH_TOKEN
      runtimeEnv:
        name: CLAUDE_CODE_OAUTH_TOKEN
