apiVersion: agentfile.build/v1
kind: Agent
metadata:
  name: hello-world
spec:
  systemPrompt:
    git:
      url: https://github.com/jujumilk3/leaked-system-prompts//openai-chatgpt5-codex_20260325.md
      ref: v0.0.1
  prompt:
    text: |
      say hi like they do in Hawaii!
  skills:
    - fs:
        projectPath: /skills/world-greetings