apiVersion: agentfile.build/v1
kind: Agent
metadata:
  name: hello-world
spec:
  systemPrompt:
    git: https://github.com/jujumilk3/leaked-system-prompts//openai-chatgpt5-codex_20260325.md
  prompt:
    text: |
      say hi like they do in Hawaii!
  skills:
    - http: https://github.com/itaysk/world-greetings-skill/archive/refs/tags/v0.0.1.tar.gz